server:
  port: 8080
  servlet:
    context-path: /api/QLTV

spring:
  datasource:
    url: "jdbc:mysql://localhost:3308/QuanLyThuVien"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect # Dialect cho MySQL
  jwt:
    valid-duration: 10 # 60s
    refreshable-duration: 1200 #1200s
    signerKey: "fjJn9RdiXSFp79TA9UhegB6WNs4PsnHO9vxJJMn2oPCniZXzHk8rLKo0UJbl41PU"
